[package]
name = "annotator"
version = "0.2.2"
description = "Spectrum annotator"
authors = ["Douwe Schulte <d.schulte@uu.nl>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/snijderlab/annotator"
edition = "2021"
rust-version = "1.82.0"

[build-dependencies]
tauri-build = { version = "2.0", features = [] }
tauri = { version = "2.0" }

[dependencies]
itertools = "0.13"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.0", features = ["protocol-asset"] }
rustyms = { version = "0.9.0-alpha.2", default-features = false, features = [
    "identification",
    "align",
    "isotopes",
    "mzdata",
] }
ordered-float = { version = "4.5", features = ["serde"] }
rayon = "1.10"
mzdata = { version = "0.35", features = ["thermo", "mzsignal", "proxi-async"] }
mzpeaks = "0.22"
mzsignal = "0.25"
tauri-plugin-dialog = "2"

[patch.crates-io]
rustyms = { path = "../../rustyms/rustyms" }
# hdf5 rs=ust crate needs a new version
hdf5 = { git = "https://github.com/aldanor/hdf5-rust.git" }
hdf5-sys = { git = "https://github.com/aldanor/hdf5-rust.git" }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
mzmlb = ["mzdata/mzmlb"]

[profile.release]
debug = true
opt-level = 3
lto = true
codegen-units = 1
